### ISSUE TITLE
Interface Tour

### ISSUE THREAD

**Issue by rhoegg** [techlahoma/discussions#2]
I got some sp... er.. unsolicited communication from Bernie Bokenyi, Market Development Specialist at F2F Events.  It was encouraging me to pre-register for the Interface Tour, which is coming to Oklahoma City in May.

http://interfacetour.com/tour/okc15/

Anyone heard of or attended this?  It looks IT focused, and possibly in line with our mission.

I'm wondering how we should involve ourselves in this (and things like it)... should we endorse and promote it?  Try to help out?  Ignore it?

**Comment by DevinClark** [comment]
What kind of involvement were you thinking?

**Comment by rhoegg** [comment]
Not sure, we could simply attend or not participate at all.  Seems like we should keep track of tech conferences here in town though.

**Comment by amandaharlin** [comment]
I'm down for going. it would be smart to attend this and the information
warfare summit, at the very least.
