### ISSUE TITLE
Is Techlahoma hosting a conference at Disney World?

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/discussions#3]
I heard it through the grapevine. I need to know so I can make arrangements as cheap as possible!

**Comment by vlucas** [comment]
Nope. :)

**Comment by DevinClark** [comment]
I think we need Oklahoma to have a Disney World first.

**Comment by seejessicacode** [comment]
Anyone have the power to label this thread "question?"

**Comment by seejessicacode** [comment]
"Nope." was pretty clear, so I'm closing my question. Thank you!
