### ISSUE TITLE
How are the Slack channels moderated?

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/discussions#4]
I get the impression that the Techlahoma slack is pretty casual and is based on the honor system, which I really like.

However, I would also like the board to consider the following ideas, though I don't know if these are all possible with Slack:
- Channels with a clear outline of their purpose.
  - Some channels are pretty obvious by name but channels like #general get treated like #random, with requests for anime suggestions or star wars discussions.
  - Also there are channels like #holywars that make no sense. People could always just ask, but people often don't like to learn the hard way that a channel is not their cup of tea.
- A clear Code of Conduct
  - I assume that Techlahoma's CoC applies to all of their slack channels. However, when matters of swearing, mom jokes, or "let me google that for you" references become a concern even when the context was purely positive, maybe a stricter CoC should be considered for certain channels. #general, #announcements, and any beginner focused channels could benefit from this.
- A slack bot in place to privately remind members how to keep our slack awesome!
  - Example: When a member joins a channel or logins for the first time in a day/week, a bot could just message them short description of that channel, a list of any rules unique to that channel, the github discussions repo, and how to contact someone if there is a serious CoC violation.

If there are no ways to implement some of these ideas without beating each other with a metaphorical ruler, then please disregard because that is not my intention. I'd just like the community slack to be more organized.

**Comment by amandaharlin** [comment]
This is great! Jess your thoughts and questions are a big help right now. Let me see if I can get my thoughts organized in here and then into a text file or in a wiki.

**Comment by johnathanmorlock** [comment]
Just chiming in from my POV (And maybe others?!?!), if it matters at all.

I guess I see general as that.. general chat. Nothing really focused with any topic. Thus, that's how I've treated it as an open discussion where most things are welcome in a sense of starting conversation. If the discussion is spun off into a channel or a more involved one where many are responding, isn't that what it is for?

I would imagine that if #general is about general tech talk or whatever (i.e. not generalized non-tech chat, etc.), wouldn't it be prudent to rename it to #generaltechtalk, or something similar?

BTW, anything I post is usually lightly salted with humor or with a general soft-hearted tone. Text doesn't portray context or emotion very well. :D

**Comment by seejessicacode** [comment]
Renaming #general to #announcements and making it read only has really helped organize the online chat.

As for moderation, how can members know who to DM when they want to report a CoC violation? 

A quick way to look up available moderators is one of those things you don't think you need until you do. Usually these matters are directed to @amandaharlin and @the-simian, but I think only people who know about the non-profit founders would know this. Even then, two people moderating a slack with 300+ members is not enough. I'd like to suggest at least 3% of the regular slack users be moderators. I have no suggestions on how to delegate that responsibility though.
