### ISSUE TITLE
How do new user groups join Techlahoma?

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/discussions#5]
I thought this was explained on techlahoma.org but I can't find anymore. Could we have a check list ready for interested user group leaders?

**Comment by seejessicacode** [comment]
Quote from techlahoma homepage as pointed out to me by Billy Maybray
"GROUP PARTICIPATION GUIDELINES

Techlahoma collects donations to support user groups by purchasing equipment, food, and supplies.

In order to qualify for support, groups need to meet about a particular topic/tech or have some otherwise concrete reason for meeting and they need at least 3 organizers or volunteers to make sure the group will thrive. Group leaders must accept and enforce the Techlahoma Code of Conduct (or another comprable CoC) and agree to be good community stewards."

**Comment by the-simian** [comment]
there's an issue where we agreed on a formal definition as well I'll need to poke around, but this all needs to go on the site as an update

**Comment by kacollins** [comment]
https://github.com/techlahoma/board_meetings/issues/29
